package br.ufpb.dsc.nexushub.model.opportunities.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import br.ufpb.dsc.nexushub.model.groups.repository.GroupRepository;import br.ufpb.dsc.nexushub.model.opportunities.domain.*;import br.ufpb.dsc.nexushub.model.opportunities.repository.*;import br.ufpb.dsc.nexushub.model.opportunities.service.impl.OpportunityServiceImpl;import br.ufpb.dsc.nexushub.model.people.domain.Human;import br.ufpb.dsc.nexushub.model.people.repository.HumanRepository;import br.ufpb.dsc.nexushub.model.projects.repository.ProjectRepository;
import java.util.*;import org.junit.jupiter.api.*;
class OpportunityServiceImplTest{
 OpportunityRepository opportunities=mock(OpportunityRepository.class);OpportunityApplicationRepository applications=mock(OpportunityApplicationRepository.class);HumanRepository humans=mock(HumanRepository.class);GroupRepository groups=mock(GroupRepository.class);ProjectRepository projects=mock(ProjectRepository.class);OpportunityServiceImpl service=new OpportunityServiceImpl(opportunities,applications,humans,groups,projects);
 @Test void listsOnlyActive(){Opportunity active=mock(Opportunity.class),inactive=mock(Opportunity.class);when(active.getRecordStatus()).thenReturn(1);when(inactive.getRecordStatus()).thenReturn(0);when(opportunities.findAll()).thenReturn(List.of(active,inactive));assertEquals(List.of(active),service.listOpenOpportunities());}
 @Test void createsOpportunity(){UUID human=UUID.randomUUID();Human publisher=mock(Human.class);when(humans.findById(human)).thenReturn(Optional.of(publisher));when(opportunities.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.createOpportunity(human,null,null,"N","D",null,human));assertThrows(IllegalArgumentException.class,()->service.createOpportunity(UUID.randomUUID(),null,null,"N","D",1,human));}
 @Test void appliesAndIsIdempotent(){UUID oppId=UUID.randomUUID(),humanId=UUID.randomUUID();Opportunity opp=mock(Opportunity.class);Human human=mock(Human.class);OpportunityApplication existing=mock(OpportunityApplication.class);when(opportunities.findById(oppId)).thenReturn(Optional.of(opp));when(humans.findById(humanId)).thenReturn(Optional.of(human));when(applications.findByOpportunityAndHuman(opp,human)).thenReturn(Optional.of(existing));assertSame(existing,service.apply(oppId,humanId,"x",humanId));when(applications.findByOpportunityAndHuman(opp,human)).thenReturn(Optional.empty());when(applications.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.apply(oppId,humanId,"x",humanId));}
 @Test void rejectsMissingApplyData(){UUID id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->service.apply(id,id,"",id));when(opportunities.findById(id)).thenReturn(Optional.of(mock(Opportunity.class)));assertThrows(IllegalArgumentException.class,()->service.apply(id,id,"",id));}
}
