package br.ufpb.dsc.nexushub.model.groups.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import br.ufpb.dsc.nexushub.model.dto.GrupoRequest;import br.ufpb.dsc.nexushub.model.groups.domain.*;import br.ufpb.dsc.nexushub.model.groups.repository.*;import br.ufpb.dsc.nexushub.model.groups.service.impl.GroupServiceImpl;import br.ufpb.dsc.nexushub.model.identity.domain.User;import br.ufpb.dsc.nexushub.model.identity.repository.UserRepository;import br.ufpb.dsc.nexushub.model.identity.service.IdentityService;import br.ufpb.dsc.nexushub.model.people.domain.Human;import br.ufpb.dsc.nexushub.model.people.repository.HumanRepository;
import java.util.*;import org.junit.jupiter.api.*;
class GroupServiceImplTest{
 GroupRepository groups=mock(GroupRepository.class);HumanRepository humans=mock(HumanRepository.class);GroupHumanMemberRepository members=mock(GroupHumanMemberRepository.class);UserRepository users=mock(UserRepository.class);IdentityService identity=mock(IdentityService.class);GroupServiceImpl service=new GroupServiceImpl(groups,humans,members,users,identity);
 @Test void listsGetsDeletes(){Group active=mock(Group.class),inactive=mock(Group.class);UUID id=UUID.randomUUID();when(active.getRecordStatus()).thenReturn(1);when(inactive.getRecordStatus()).thenReturn(0);when(groups.findAll()).thenReturn(List.of(active,inactive));when(groups.findById(id)).thenReturn(Optional.of(active));assertEquals(List.of(active),service.listActiveGroups());assertSame(active,service.getGroup(id));service.deleteGroup(id);verify(groups).delete(active);assertThrows(IllegalArgumentException.class,()->service.getGroup(UUID.randomUUID()));}
 @Test void resolvesResponsible(){UUID id=UUID.randomUUID();Group group=mock(Group.class);GroupHumanMember member=mock(GroupHumanMember.class);Human human=mock(Human.class);when(groups.findById(id)).thenReturn(Optional.of(group));when(members.findByGroup(group)).thenReturn(List.of(member));when(member.getAdmin()).thenReturn(true);when(member.getHuman()).thenReturn(human);when(human.getName()).thenReturn("Ana");assertEquals("Ana",service.getResponsibleName(id));when(member.getAdmin()).thenReturn(false);assertNull(service.getResponsibleName(id));}
 @Test void addsOrReusesMember(){UUID gid=UUID.randomUUID(),hid=UUID.randomUUID();Group group=mock(Group.class);Human human=mock(Human.class);GroupHumanMember existing=mock(GroupHumanMember.class);when(groups.findById(gid)).thenReturn(Optional.of(group));when(humans.findById(hid)).thenReturn(Optional.of(human));when(members.findByGroupAndHuman(group,human)).thenReturn(Optional.of(existing));assertSame(existing,service.addHumanToGroup(gid,hid,true,hid));when(members.findByGroupAndHuman(group,human)).thenReturn(Optional.empty());when(members.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.addHumanToGroup(gid,hid,false,hid));}
 @Test void rejectsMissingMemberData(){UUID id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->service.addHumanToGroup(id,id,false,id));when(groups.findById(id)).thenReturn(Optional.of(mock(Group.class)));assertThrows(IllegalArgumentException.class,()->service.addHumanToGroup(id,id,false,id));}
 @Test void createsSimpleGroupWithFallbackUpdater(){UUID id=UUID.randomUUID();User first=mock(User.class);Group saved=mock(Group.class);when(first.getId()).thenReturn(id);when(identity.firstUser()).thenReturn(first);when(groups.save(any())).thenReturn(saved);assertSame(saved,service.createGroup("N","D",null,null,null));}
 @Test void createsGroupFromRequest(){UUID uid=UUID.randomUUID(),hid=UUID.randomUUID(),gid=UUID.randomUUID();User user=mock(User.class);Human human=mock(Human.class);Group group=mock(Group.class);when(user.getId()).thenReturn(uid);when(user.getHuman()).thenReturn(human);when(human.getId()).thenReturn(hid);when(group.getId()).thenReturn(gid);when(users.findById(uid)).thenReturn(Optional.of(user));when(groups.save(any())).thenReturn(group);when(groups.findById(gid)).thenReturn(Optional.of(group));when(humans.findById(hid)).thenReturn(Optional.of(human));when(members.save(any())).thenAnswer(i->i.getArgument(0));GrupoRequest request=new GrupoRequest("N","D","comunidade","R","restrito","",null,uid);assertSame(group,service.createGroup(request));}
 @Test void requiresCreator(){GrupoRequest request=new GrupoRequest("N","D",null,null,null,null,null,null);assertThrows(IllegalArgumentException.class,()->service.createGroup(request));}
}
