package br.ufpb.dsc.nexushub.model.projects.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import br.ufpb.dsc.nexushub.model.dto.*;import br.ufpb.dsc.nexushub.model.groups.repository.GroupRepository;import br.ufpb.dsc.nexushub.model.identity.domain.User;import br.ufpb.dsc.nexushub.model.identity.repository.UserRepository;import br.ufpb.dsc.nexushub.model.identity.service.IdentityService;import br.ufpb.dsc.nexushub.model.people.domain.Human;import br.ufpb.dsc.nexushub.model.people.repository.HumanRepository;import br.ufpb.dsc.nexushub.model.projects.domain.*;import br.ufpb.dsc.nexushub.model.projects.repository.*;import br.ufpb.dsc.nexushub.model.projects.service.impl.ProjectServiceImpl;
import java.util.*;import org.junit.jupiter.api.*;
class ProjectServiceImplTest{
 ProjectRepository projects=mock(ProjectRepository.class);ProjectTagRepository projectTags=mock(ProjectTagRepository.class);TagRepository tags=mock(TagRepository.class);ProjectRequestRepository requests=mock(ProjectRequestRepository.class);ProjectHumanMemberRepository members=mock(ProjectHumanMemberRepository.class);HumanRepository humans=mock(HumanRepository.class);GroupRepository groups=mock(GroupRepository.class);UserRepository users=mock(UserRepository.class);IdentityService identity=mock(IdentityService.class);ProjectServiceImpl service=new ProjectServiceImpl(projects,projectTags,tags,requests,members,humans,groups,users,identity);
 @Test void listsFiltersAndGets(){Project active=mock(Project.class),inactive=mock(Project.class);Human owner=mock(Human.class);UUID id=UUID.randomUUID();when(active.getRecordStatus()).thenReturn(1);when(inactive.getRecordStatus()).thenReturn(0);when(active.getOwner()).thenReturn(owner);when(owner.getName()).thenReturn("Ana");when(projects.findAll()).thenReturn(List.of(active,inactive));when(projects.findById(id)).thenReturn(Optional.of(active));assertEquals(1,service.listPublishedProjects().size());assertEquals(1,service.listProjects(null,"ana").size());assertEquals(1,service.listProjectsByAuthor("Ana").size());assertEquals(1,service.listHotProjects().size());assertEquals(1,service.listRecentProjects().size());assertEquals(1,service.listCollaborativeProjects().size());assertSame(active,service.getProject(id));assertThrows(IllegalArgumentException.class,()->service.getProject(UUID.randomUUID()));}
 @Test void createsProject(){UUID hid=UUID.randomUUID(),actor=UUID.randomUUID();Human human=mock(Human.class);when(humans.findById(hid)).thenReturn(Optional.of(human));when(projects.save(any())).thenAnswer(i->i.getArgument(0));when(members.save(any())).thenAnswer(i->i.getArgument(0));Project result=service.createProject(hid,null,"N","R","G",null,actor);assertNotNull(result);verify(members).save(any());assertThrows(IllegalArgumentException.class,()->service.createProject(UUID.randomUUID(),null,"N","R","G",1,actor));}
 @Test void requestsMembershipAndRejectsDuplicate(){UUID pid=UUID.randomUUID(),hid=UUID.randomUUID();Project project=mock(Project.class);Human human=mock(Human.class);when(projects.findById(pid)).thenReturn(Optional.of(project));when(humans.findById(hid)).thenReturn(Optional.of(human));when(requests.findByProjectAndRequester(project,human)).thenReturn(Optional.empty());when(requests.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.requestMembership(pid,hid,"motivo",hid));when(requests.findByProjectAndRequester(project,human)).thenReturn(Optional.of(mock(ProjectRequest.class)));assertThrows(IllegalArgumentException.class,()->service.requestMembership(pid,hid,"m",hid));}
 @Test void approvesExistingOrNewMember(){UUID rid=UUID.randomUUID(),eid=UUID.randomUUID();ProjectRequest request=mock(ProjectRequest.class);Project project=mock(Project.class);Human requester=mock(Human.class),evaluator=mock(Human.class);ProjectHumanMember existing=mock(ProjectHumanMember.class);when(requests.findById(rid)).thenReturn(Optional.of(request));when(humans.findById(eid)).thenReturn(Optional.of(evaluator));when(request.getProject()).thenReturn(project);when(request.getRequester()).thenReturn(requester);when(members.findByProjectAndHuman(project,requester)).thenReturn(Optional.of(existing));assertSame(existing,service.approveMembershipRequest(rid,eid,eid));verify(request).approve(evaluator,eid);when(members.findByProjectAndHuman(project,requester)).thenReturn(Optional.empty());when(members.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.approveMembershipRequest(rid,eid,eid));}
 @Test void respondsRejected(){UUID rid=UUID.randomUUID(),uid=UUID.randomUUID();User evaluator=mock(User.class);Human human=mock(Human.class);ProjectRequest request=mock(ProjectRequest.class);when(identity.firstUser()).thenReturn(evaluator);when(evaluator.getHuman()).thenReturn(human);when(evaluator.getId()).thenReturn(uid);when(requests.findById(rid)).thenReturn(Optional.of(request));service.respondMembershipRequest(rid,false);verify(request).reject(human,uid);}
 @Test void validatesMissingRequests(){UUID id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->service.requestMembership(id,id,"m",id));assertThrows(IllegalArgumentException.class,()->service.approveMembershipRequest(id,id,id));}
 @Test void listsByTag(){Project project=mock(Project.class);ProjectTag link=mock(ProjectTag.class);Human owner=mock(Human.class);when(link.getProject()).thenReturn(project);when(project.getRecordStatus()).thenReturn(1);when(project.getOwner()).thenReturn(owner);when(owner.getName()).thenReturn("Ana");when(projectTags.findByTag_NameIgnoreCase("java")).thenReturn(List.of(link));assertEquals(List.of(project),service.listProjects(" java ","Ana"));}
 @Test void createsFromDtoAndSynchronizesTags(){UUID uid=UUID.randomUUID(),hid=UUID.randomUUID();User user=mock(User.class);Human human=mock(Human.class);when(user.getId()).thenReturn(uid);when(user.getHuman()).thenReturn(human);when(human.getId()).thenReturn(hid);when(users.findById(uid)).thenReturn(Optional.of(user));when(humans.findById(hid)).thenReturn(Optional.of(human));when(projects.save(any())).thenAnswer(i->i.getArgument(0));when(members.save(any())).thenAnswer(i->i.getArgument(0));when(tags.findByNameIgnoreCase(anyString())).thenReturn(Optional.empty());when(tags.save(any())).thenAnswer(i->i.getArgument(0));ProjetoRequest dto=new ProjetoRequest("N","R","G",null,"invalid","Java, Spring","2",null,null,uid,null,null,null,50);Project result=service.createProject(dto);assertNotNull(result);verify(projectTags,times(2)).save(any(ProjectTag.class));}
 @Test void requestsFromDtoByEmail(){UUID pid=UUID.randomUUID(),uid=UUID.randomUUID(),hid=UUID.randomUUID();User user=mock(User.class);Human human=mock(Human.class);Project project=mock(Project.class);when(user.getId()).thenReturn(uid);when(user.getHuman()).thenReturn(human);when(human.getId()).thenReturn(hid);when(users.findByEmail("a@b.com")).thenReturn(Optional.of(user));when(projects.findById(pid)).thenReturn(Optional.of(project));when(humans.findById(hid)).thenReturn(Optional.of(human));when(requests.findByProjectAndRequester(project,human)).thenReturn(Optional.empty());when(requests.save(any())).thenAnswer(i->i.getArgument(0));assertNotNull(service.requestMembership(new SolicitacaoRequest(pid,null," A@B.COM ",null,"motivo")));}
 @Test void respondsApprovedAndListsRequests(){UUID pid=UUID.randomUUID(),rid=UUID.randomUUID(),uid=UUID.randomUUID(),hid=UUID.randomUUID();User user=mock(User.class);Human human=mock(Human.class);Project project=mock(Project.class);ProjectRequest request=mock(ProjectRequest.class);when(identity.firstUser()).thenReturn(user);when(user.getHuman()).thenReturn(human);when(user.getId()).thenReturn(uid);when(human.getId()).thenReturn(hid);when(projects.findById(pid)).thenReturn(Optional.of(project));when(requests.findByProject(project)).thenReturn(List.of(request));when(requests.findById(rid)).thenReturn(Optional.of(request));when(humans.findById(hid)).thenReturn(Optional.of(human));when(request.getProject()).thenReturn(project);when(request.getRequester()).thenReturn(human);when(members.save(any())).thenAnswer(i->i.getArgument(0));assertEquals(1,service.listRequestsByProject(pid).size());service.respondMembershipRequest(rid,true);verify(request).approve(human,uid);}
 @Test void validatesDtoActors(){UUID pid=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->service.createProject(new ProjetoRequest("N","R",null,null,null,null,null,null,null,null,null,null,null,0)));assertThrows(IllegalArgumentException.class,()->service.requestMembership(new SolicitacaoRequest(pid,null,null,null,"m")));assertThrows(IllegalArgumentException.class,()->service.requestMembership(new SolicitacaoRequest(pid,null,"missing@x.com",null,"m")));}
}
