package br.ufpb.dsc.nexushub.model.identity.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import br.ufpb.dsc.nexushub.model.identity.domain.*;import br.ufpb.dsc.nexushub.model.identity.repository.*;import br.ufpb.dsc.nexushub.model.identity.service.impl.IdentityServiceImpl;import br.ufpb.dsc.nexushub.model.people.domain.Human;import br.ufpb.dsc.nexushub.model.people.repository.HumanRepository;
import java.util.*;import org.junit.jupiter.api.*;import org.springframework.security.crypto.password.PasswordEncoder;
class IdentityServiceImplTest{
 UserRepository users=mock(UserRepository.class);RoleRepository roles=mock(RoleRepository.class);HumanRepository humans=mock(HumanRepository.class);PasswordEncoder encoder=mock(PasswordEncoder.class);IdentityServiceImpl service=new IdentityServiceImpl(users,roles,humans,encoder);
 @BeforeEach void saves(){when(humans.save(any())).thenAnswer(i->i.getArgument(0));when(users.save(any())).thenAnswer(i->i.getArgument(0));when(encoder.encode(anyString())).thenReturn("hash");}
 @Test void reportsUsers(){when(users.count()).thenReturn(1L);assertTrue(service.hasUsers());when(users.count()).thenReturn(0L);assertFalse(service.hasUsers());}
 @Test void registersNormalizedUserAndDefaultRole(){Role role=mock(Role.class);when(roles.findByName("STUDENT")).thenReturn(Optional.of(role));User user=service.registerUser(" Ana "," ANA@MAIL.COM ","secret",null,null);assertEquals("ana@mail.com",user.getEmail());assertSame(role,user.getRole());}
 @Test void createsMissingNamedRole(){when(roles.findByName("ADMIN")).thenReturn(Optional.empty());when(roles.save(any())).thenAnswer(i->i.getArgument(0));assertEquals("ADMIN",service.registerUser("Ana","a@b.com","secret"," admin ",null).getRole().getName());}
 @Test void rejectsDuplicate(){when(users.findByEmail("a@b.com")).thenReturn(Optional.of(mock(User.class)));assertThrows(IllegalArgumentException.class,()->service.registerUser("A","a@b.com","x",null,null));}
 @Test void authenticatesAndRejectsPassword(){User user=mock(User.class);when(user.getPasswordHash()).thenReturn("hash");when(users.findByEmail("a@b.com")).thenReturn(Optional.of(user));when(encoder.matches("ok","hash")).thenReturn(true);assertSame(user,service.authenticate(" A@B.COM ","ok").orElseThrow());verify(user).registerAccess();assertTrue(service.authenticate("a@b.com","bad").isEmpty());}
 @Test void changesPasswords(){UUID id=UUID.randomUUID(),actor=UUID.randomUUID();User user=mock(User.class);when(user.getId()).thenReturn(id);when(users.findById(id)).thenReturn(Optional.of(user));service.changePassword(id,"new",actor);verify(user).changePassword("hash",actor);when(users.findByEmail("a@b.com")).thenReturn(Optional.of(user));service.changePasswordByEmail("A@B.COM","new");verify(user).changePassword("hash",id);}
 @Test void rejectsPasswordChanges(){UUID id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->service.changePassword(id,"x",id));assertThrows(IllegalArgumentException.class,()->service.changePasswordByEmail("x@y.com","x"));}
 @Test void updatesProfileWithOptionalPassword(){UUID id=UUID.randomUUID();User user=mock(User.class);Human human=mock(Human.class);when(users.findById(id)).thenReturn(Optional.of(user));when(user.getHuman()).thenReturn(human);when(users.save(user)).thenReturn(user);assertSame(user,service.updateUserProfile(id," Ana "," A@B.COM ","123456",null));verify(user).changeEmail("a@b.com",id);verify(user).changePassword("hash",id);assertSame(user,service.updateUserProfile(id,"Ana","a@b.com",null,null));}
 @Test void findsFirstAndByEmail(){User user=mock(User.class);when(users.findAll()).thenReturn(List.of(user));when(users.findByEmail("a@b.com")).thenReturn(Optional.of(user));assertSame(user,service.firstUser());assertSame(user,service.findByEmail(" A@B.COM "));when(users.findAll()).thenReturn(List.of());assertThrows(IllegalStateException.class,service::firstUser);assertThrows(IllegalArgumentException.class,()->service.findByEmail("x@y.com"));}
}
