spring:
  application:
    name: nexus-hub
  datasource:
    url: jdbc:h2:mem:nexushub
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
